-- CRIAÇÃO BASE DE DADOS --
CREATE DATABASE carglass
GO

-- CRIAÇÃO DE TABELAS --
USE carglass
GO

-- TABELA EMPRESA --
BEGIN TRAN

	CREATE TABLE Empresa (
		ID_EMPRESA		INT	IDENTITY(1,1) NOT NULL,
		UF				CHAR(2) NOT NULL,
		NOME_FANTASIA	VARCHAR(30) NOT NULL,
		CNPJ			VARCHAR(14) NOT NULL,
		CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA)
	)

ROLLBACK
--COMMIT

-- TABELA FORNECEDOR --
BEGIN TRAN

	CREATE TABLE Fornecedor (
		ID_FORNECEDOR	INT	IDENTITY(1,1) NOT NULL,
		ID_EMPRESA		INT NOT NULL,
		NOME			VARCHAR(30) NOT NULL,
		CPFCNPJ			VARCHAR(14) NOT NULL,	
		DHCADASTRO		DATETIME DEFAULT GETDATE() NOT NULL,
		CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR),
		CONSTRAINT FK_FORNECEDOR_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES Empresa (ID_EMPRESA)
	)

ROLLBACK
--COMMIT

-- TABELA FORNECEDOR PF --
BEGIN TRAN

	CREATE TABLE FornecedorPF (
		ID_FORNECEDOR	INT NOT NULL,
		RG				VARCHAR(20) NOT NULL,	
		DTNASCIMENTO	DATE NOT NULL,	
		CONSTRAINT PK_FORNECEDORPF PRIMARY KEY (ID_FORNECEDOR),
		CONSTRAINT FK_FORNECEDORPF_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES Fornecedor (ID_FORNECEDOR)
	)

ROLLBACK
--COMMIT

-- TABELA TELEFONE FORNECEDOR --
BEGIN TRAN

	CREATE TABLE Telefone_Fornecedor (
		ID_TELEFONE		INT IDENTITY(1,1)  NOT NULL,
		ID_FORNECEDOR	INT  NOT NULL,
		DDD				CHAR(2)  NOT NULL,
		TELEFONE		VARCHAR(9)  NOT NULL,
		CONSTRAINT PK_TELEFONE PRIMARY KEY (ID_TELEFONE),
		CONSTRAINT FK_TELEFONE_FORNECEDOR_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES Fornecedor (ID_FORNECEDOR)
	)

ROLLBACK
--COMMIT