USE CARGLASS
GO

DECLARE @ID_EMPRESA INT;
SET @ID_EMPRESA = @ID_EMPRESA; --VARIAVEL DO ID EMPRESA

-- SELECT --
	SELECT * FROM EMPRESA WHERE ID_EMPRESA = @ID_EMPRESA

-- UPDATE --
BEGIN TRAN

	UPDATE EMPRESA
	SET UF = 'RJ'
	WHERE ID_EMPRESA = @ID_EMPRESA

ROLLBACK
--COMMIT

-- DELETE --
BEGIN TRAN

	DELETE FROM EMPRESA 
	WHERE ID_EMPRESA = @ID_EMPRESA

ROLLBACK
--COMMIT

-- INSERT --
BEGIN TRAN

	INSERT INTO EMPRESA (UF,NOME_FANTASIA,CNPJ)
	VALUES ('RJ','TESTE INSERT','12345678901234')

ROLLBACK
--COMMIT